# Generated by Django 5.2.7 on 2026-03-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone_alter_user_email_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='تلفن'),
        ),
    ]
