# Generated by Django 5.2.7 on 2026-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='code',
            field=models.IntegerField(),
        ),
    ]
