# Generated by Django 5.2.7 on 2026-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_full_name_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
