# Generated by Django 5.2.7 on 2026-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default='ر', max_length=30, verbose_name='عنوان مشخصات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(verbose_name='متن مشخصات'),
        ),
    ]
