# Generated by Django 5.2.7 on 2026-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_information_title_alter_information_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.CharField(verbose_name='متن مشخصات'),
        ),
    ]
