# Generated by Django 5.2.7 on 2026-03-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_information_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'مشخصات', 'verbose_name_plural': 'مشخصات محصولات'},
        ),
    ]
