# Generated by Django 5.2.7 on 2026-03-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_information_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.CharField(verbose_name='متن '),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان '),
        ),
    ]
