# Generated by Django 5.2.7 on 2026-03-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_information_product_alter_information_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(verbose_name='متن '),
        ),
    ]
