# Generated by Django 5.2.7 on 2026-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_information_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان '),
        ),
    ]
