# Generated by Django 5.2.7 on 2026-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.BigIntegerField(default=0, verbose_name='قیمت با تخفیف'),
            preserve_default=False,
        ),
    ]
