# Generated by Django 5.2.7 on 2026-03-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_color_alter_orderitem_size'),
        ('product', '0016_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='سایز'),
        ),
    ]
