# Generated by Django 5.2.7 on 2026-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(verbose_name='سایز'),
        ),
    ]
