# Generated by Django 5.2.7 on 2026-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_discountcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تحفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
